using System.Text;

namespace EFCore.DomainModelGenerator.CodeGeneration;

internal class DomainRegistratorGeneration(string ns, DomainMetadata[] domains)
{
  public string GenerateCode()
  {
    var registrationCode = GenerateRegistrationCode();
    return
      $$"""
        // <auto-generated/>

        namespace {{ns}};

        public static class DomainRegistrationHelper
        {
          public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDomains(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
          {
          {{registrationCode}}
          return services;
          }
        }
        """;
  }

  private string GenerateRegistrationCode()
  {
    var codes = domains.Select(GenerateSingleRegistrationCode);
    var sb = new StringBuilder();
    foreach (var code in codes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }

  private static string GenerateSingleRegistrationCode(DomainMetadata domain)
  {
    return $"services.AddScoped<{domain.ReadonlyDomainClass}>().AddScoped<{domain.WritableDomainClass}>();";
  }
}
