using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator.CodeGeneration;

internal class DomainModelGeneration(string ns, INamedTypeSymbol contextType, DomainMetadata domain)
{
  private string Namespace { get; } = ns;
  private INamedTypeSymbol ContextType { get; } = contextType;
  private string DomainClassName { get; } = domain.DomainClassName;
  private IEnumerable<DomainSetMetadata> DomainSetMetadata { get; } = domain.DomainSetMetadata;

  public string GenerateCode()
  {
    var contextType = ContextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var readonlyPropsCode = GenerateJoinedPropertyCode(false);
    var writablePropsCode = GenerateJoinedPropertyCode(true);
    return
      $$"""
        // <auto-generated/>

        namespace {{Namespace}};

        public partial class {{DomainClassName}}({{contextType}} db)
        {
        protected {{contextType}} Db => db;

        {{readonlyPropsCode}}
        }

        public partial class Writable{{DomainClassName}}({{contextType}} db) : {{DomainClassName}}(db)
        {
        {{writablePropsCode}}
        }
        """;
  }

  private static string GeneratePropertyCode(DomainSetMetadata x, bool writable)
  {
    var accessibility = x.IsPrivate ? "protected" : "public";
    var newKey = writable ? "new" : "";
    var newKeyword = writable ? "new" : "";
    var collectionType = writable ? "global::Microsoft.EntityFrameworkCore.DbSet" : "global::System.Linq.IQueryable";
    var elementType = x.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var type = $"{collectionType}<{elementType}>";
    return
      $"{accessibility} {newKeyword} {type} {x.MappedName} => Db.{x.OriginalName};";
  }

  private string GenerateJoinedPropertyCode(bool writable)
  {
    var propertyCodes = DomainSetMetadata.Select(x => GeneratePropertyCode(x, writable));
    // Environment.NewLine is not allowed in Roslyn code, thus building codes with StringBuilder.
    var sb = new StringBuilder();
    foreach (var code in propertyCodes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }
}
