using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator.CodeGeneration;

internal class DomainModelGeneration(string ns, INamedTypeSymbol contextType, DomainMetadata domain)
{
  public string GenerateCode()
  {
    var contextClass = contextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var readonlyPropsCode = GenerateJoinedPropertyCode(false);
    var writablePropsCode = GenerateJoinedPropertyCode(true);
    return
      $$"""
        // <auto-generated/>

        namespace {{ns}};

        public partial class {{domain.ReadonlyDomainClass}}({{contextClass}} db)
        {
        protected {{contextClass}} Db => db;

        {{readonlyPropsCode}}
        }

        public partial class {{domain.WritableDomainClass}}({{contextClass}} db) : {{domain.ReadonlyDomainClass}}(db)
        {
        {{writablePropsCode}}
        }
        """;
  }

  private static string GeneratePropertyCode(DomainSetMetadata x, bool writable)
  {
    var accessibility = x.Hidden ? "protected" : "public";
    var newKeyword = writable ? "new" : "";
    var collectionType = writable ? "global::Microsoft.EntityFrameworkCore.DbSet" : "global::System.Linq.IQueryable";
    var elementType = x.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var type = $"{collectionType}<{elementType}>";
    return
      $"{accessibility} {newKeyword} {type} {x.MappedName} => Db.{x.OriginalName};";
  }

  private string GenerateJoinedPropertyCode(bool writable)
  {
    var propertyCodes = domain.DomainSetMetadata.Select(x => GeneratePropertyCode(x, writable));
    // Environment.NewLine is not allowed in Roslyn code, thus building codes with StringBuilder.
    var sb = new StringBuilder();
    foreach (var code in propertyCodes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }
}
