namespace EFCore.DomainModelGenerator;

internal static class DomainContextAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>
    #pragma warning disable CS9113

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainContextAttribute(string domainModelNameSpace) : Attribute;
    """;
}
