namespace EFCore.DomainModelGenerator;

internal static class DomainSetAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainSetAttribute(string domainName = null, bool isPrivate = false) : Attribute
    {
      public string DomainName { get; } = domainName;
      public bool IsPrivate { get; } = isPrivate;
    }
    """;
}
