namespace EFCore.DomainModelGenerator;

internal static class DomainSetAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainSetAttribute(string domainName = null, string mappedName = null, bool asDbSet = false, bool isPrivate = false) : Attribute
    {
      public string DomainName { get; } = domainName;
      public string MappedName { get; } = mappedName;
      public bool AsDbSet { get; } = asDbSet;
      public bool IsPrivate { get; } = isPrivate;
    }
    """;
}
