using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator;

internal class DomainModelSource
{
  public required string Namespace { get; set; }
  public required string DomainClassName { get; set; }
  public required INamedTypeSymbol ContextType { get; set; }
  public required IEnumerable<DomainSetMetadata> DomainSetMetadata { get; set; }

  public string GenerateCode()
  {
    var contextType = ContextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var propertyCode = GenerateJoinedPropertyCode();
    return
      $$"""
        // <auto-generated/>

        namespace {{Namespace}};
        using Microsoft.EntityFrameworkCore;

        public partial class {{DomainClassName}}({{contextType}} db)
        {
          {{propertyCode}}
        }
        """;
  }

  private static string GeneratePropertyCode(DomainSetMetadata x)
  {
    var accessibility = x.IsPrivate ? "private" : "public";
    var type = x.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    return
      $"{accessibility} Microsoft.EntityFrameworkCore.DbSet<{type}> {x.MappedName} => db.{x.OriginalName};";
  }

  private string GenerateJoinedPropertyCode()
  {
    var propertyCodes = DomainSetMetadata.Select(GeneratePropertyCode);
    // Environment.NewLine is not allowed in Roslyn code, thus building codes with StringBuilder.
    var sb = new StringBuilder();
    foreach (var code in propertyCodes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }
}

internal record DomainSetMetadata
{
  public required string DomainName { get; set; }
  public required string MappedName { get; set; }
  public required string OriginalName { get; set; }
  public required ITypeSymbol ElementType { get; set; }
  public required bool IsPrivate { get; set; }
}
