using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator;

internal class DomainRegistrationSource
{
  public string Namespace { get; set; } = null!;
  public IEnumerable<ISymbol> DomainModelSymbols { get; set; } = null!;

  public string GenerateCode()
  {
    var registrationCode = GenerateRegistrationCode();
    return
      $$"""
        // <auto-generated/>

        namespace {{Namespace}};

        public static class DomainRegistrationHelper
        {
          public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddDomains(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
          {
          {{registrationCode}}
          return services;
          }
        }
        """;
  }

  private string GenerateRegistrationCode()
  {
    var codes = DomainModelSymbols.Select(GenerateSingleRegistrationCode);
    var sb = new StringBuilder();
    foreach (var code in codes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }

  private static string GenerateSingleRegistrationCode(ISymbol symbol)
  {
    var typeExpr = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    return $"services.AddScoped<{typeExpr}>();";
  }
}
