using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator;

internal class DomainModelSource
{
  public string Namespace { get; set; } = null!;
  public string DomainClassName { get; set; } = null!;
  public INamedTypeSymbol ContextType { get; set; } = null!;
  public IEnumerable<DomainSetMetadata> DomainSetMetadata { get; set; } = null!;

  public string GenerateCode()
  {
    var contextType = ContextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var propertyCode = GenerateJoinedPropertyCode();
    return
      $$"""
        // <auto-generated/>

        namespace {{Namespace}};

        public partial class {{DomainClassName}}({{contextType}} db)
        {
        {{propertyCode}}
        }
        """;
  }

  private static string GeneratePropertyCode(DomainSetMetadata x)
  {
    var accessibility = x.IsPrivate ? "private" : "public";
    var type = x.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    return
      $"{accessibility} {type} {x.MappedName} => db.{x.OriginalName};";
  }

  private string GenerateJoinedPropertyCode()
  {
    var propertyCodes = DomainSetMetadata.Select(GeneratePropertyCode);
    // Environment.NewLine is not allowed in Roslyn code, thus building codes with StringBuilder.
    var sb = new StringBuilder();
    foreach (var code in propertyCodes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }
}

internal record DomainSetMetadata
{
  public string DomainName { get; set; } = null!;
  public string MappedName { get; set; } = null!;
  public string OriginalName { get; set; } = null!;
  public ITypeSymbol ElementType { get; set; } = null!;
  public bool IsPrivate { get; set; }
}
