using System.Text;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator;

internal class DomainModelSource(string ns, INamedTypeSymbol contextType, DomainMetadata domain)
{
  private string Namespace { get; } = ns;
  private INamedTypeSymbol ContextType { get; } = contextType;
  private string DomainClassName { get; } = domain.DomainClassName;
  private IEnumerable<DomainSetMetadata> DomainSetMetadata { get; } = domain.DomainSetMetadata;

  public string GenerateCode()
  {
    var contextType = ContextType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    var propertyCode = GenerateJoinedPropertyCode();
    return
      $$"""
        // <auto-generated/>

        namespace {{Namespace}};

        public partial class {{DomainClassName}}({{contextType}} db)
        {
        {{propertyCode}}
        }
        """;
  }

  private static string GeneratePropertyCode(DomainSetMetadata x)
  {
    var accessibility = x.IsPrivate ? "private" : "public";
    var type = x.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    return
      $"{accessibility} {type} {x.MappedName} => db.{x.OriginalName};";
  }

  private string GenerateJoinedPropertyCode()
  {
    var propertyCodes = DomainSetMetadata.Select(GeneratePropertyCode);
    // Environment.NewLine is not allowed in Roslyn code, thus building codes with StringBuilder.
    var sb = new StringBuilder();
    foreach (var code in propertyCodes)
    {
      sb.AppendLine(code);
    }

    return sb.ToString();
  }
}
