namespace EFCore.DomainModelGenerator.ConstantSource;

internal static class AccessEnumSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    public enum Access
    {
      Public = 0,
      Internal = 1,
      Protected = 2,
    }
    """;
}
