namespace EFCore.DomainModelGenerator.ConstantSource;

internal static class DomainContextAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainContextAttribute : Attribute;
    """;
}
