namespace EFCore.DomainModelGenerator.ConstantSource;

internal static class DomainModelAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;
    using System;

    // This attribute is intended to be used only as a marker for partial domain model classes.
    // Therefore, it should not be applied to derived classes.
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainModelAttribute(string domainName) : Attribute
    {
      public string DomainName { get; } = domainName;
    }
    """;
}
