namespace EFCore.DomainModelGenerator.ConstantSource;

internal static class DomainModelDependsOnAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    internal sealed class DomainModelDependsOnAttribute(Type dependency, string mappedName = null): Attribute
    {
      public Type Dependency { get; } = dependency;
      public string MappedName { get; } = mappedName;
    }
    """;
}
