namespace EFCore.DomainModelGenerator.ConstantSource;

internal static class DomainSetAttributeSource
{
  public const string Source =
    """
    // <auto-generated/>

    namespace EFCore.DomainModelGenerator;

    using System;

    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = false)]
    internal sealed class DomainSetAttribute(string domainName = null, string mappedName = null, bool hidden = false) : Attribute
    {
      public string DomainName { get; } = domainName;
      public string MappedName { get; } = mappedName;
      public bool Hidden { get; } = hidden;
    }
    """;
}
