using EFCore.DomainModelGenerator.GenerationStep;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator.Emissions;

internal static class ModelEmission
{
  public static void Emit(SourceProductionContext context, IEnumerable<MetadataGroup> groups)
  {
    foreach (var group in groups)
    {
      var impl = new CodeGenerationImpl(group);
      context.AddSource(impl.FileName, impl.GenerateCode());
    }
  }
}

file class CodeGenerationImpl(MetadataGroup group)
{
  private readonly ContextMetadata _context = group.Contexts.First();
  private readonly MarkedModelMetadata _model = group.Model;
  private readonly IEnumerable<SetMetadata> _sets = group.Sets;

  public string FileName => $"{_model.ModelName}.g.cs";

  public string GenerateCode()
  {
    return
      $$"""
        // <auto-generated/>

        namespace {{_context.Namespace}};
        using global::Microsoft.EntityFrameworkCore;
        using global::System.Linq;

        public partial class {{_model.ModelName}}({{_context.ContextType}} db)
        {
        protected {{_context.ContextType}} Db => db;

        {{string.Join("\n", _sets.Select(static set => SinglePropertyLine(set, writable: false)))}}
        }

        public partial class Writable{{_model.ModelName}}({{_context.ContextType}} db) : {{_model.ModelName}}(db)
        {
        {{string.Join("\n", _sets.Select(static set => SinglePropertyLine(set, writable: true)))}}
        }
        """;
  }

  private static string SinglePropertyLine(SetMetadata set, bool writable)
  {
    var accessibility = writable ? set.WritableAccessibility : set.ReadonlyAccessibility;
    var newKeyword = writable ? "new" : "";
    var collectionType = writable ? "DbSet" : "IQueryable";
    var elementType = set.ElementType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    return $"{accessibility} {newKeyword} {collectionType}<{elementType}> {set.MappedName} => Db.{set.OriginalName};";
  }
}
