using EFCore.DomainModelGenerator.GenerationStep;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator.Emissions;

internal static class RegistratorEmission
{
  public static void Emit(SourceProductionContext context, IEnumerable<MetadataGroup> groups)
  {
    var gs = groups.ToArray();
    var firstContextMetadata = gs.FirstOrDefault()?.Contexts.First();
    if (firstContextMetadata is null) return;
    context.AddSource("DomainRegistration.g.cs", GenerateCode(firstContextMetadata, gs));
  }

  private static string GenerateCode(ContextMetadata contextMetadata, IEnumerable<MetadataGroup> groups)
  {
    return
      $$"""
        // <auto-generated/>

        namespace {{contextMetadata.Namespace}};
        using global::Microsoft.Extensions.DependencyInjection;

        public static class DomainRegistration
        {
        public static IServiceCollection AddDomains(this IServiceCollection services)
        {
        {{string.Join("\n", groups.Select(GetLine))}}
        return services;
        }
        }
        """;
  }

  private static string GetLine(MetadataGroup group)
  {
    var model = group.Model;
    return $"services.AddScoped<{model.ModelName}>().AddScoped<Writable{model.ModelName}>();";
  }
}
