using EFCore.DomainModelGenerator.Steps;
using Microsoft.CodeAnalysis;

namespace EFCore.DomainModelGenerator.Emissions;

internal static class RegistratorEmission
{
  public static void Emit(SourceProductionContext context, IEnumerable<MetadataGroup> groups)
  {
    var gs = groups.ToArray();
    var firstGroup = gs.FirstOrDefault();
    if (firstGroup is null) return;
    context.AddSource("DomainRegistration.g.cs", GenerateCode(firstGroup, gs));
  }

  private static string GenerateCode(MetadataGroup firstGroup, IEnumerable<MetadataGroup> groups)
  {
    var config = firstGroup.Config;
    var models = groups.Select(x => x.Model);
    return
      $$"""
        // <auto-generated/>

        namespace {{firstGroup.Config.DomainRegistrationNamespace}};
        using global::Microsoft.Extensions.DependencyInjection;
        {{string.Join("\n", models.Select(GetUsingDirective))}}

        public static class DomainRegistration
        {
        public static IServiceCollection AddDomains(this IServiceCollection services)
        {
        {{string.Join("\n", groups.Select(GetLine))}}
        return services;
        }
        }
        """;

    string GetUsingDirective(ModelMetadata model) =>
      $"using {config.GetDomainNamespace(model.DomainName)};";
  }

  private static string GetLine(MetadataGroup group)
  {
    var model = group.Model;
    return $"services.AddScoped<{model.ModelName}>().AddScoped<Writable{model.ModelName}>();";
  }
}
