using Microsoft.EntityFrameworkCore;
using SampleProgram.Entities;
using SampleProgram.Repository;

namespace SampleProgram.Domains;

// This class should be generated by the source generator
public partial class CustomersDomain(PrimaryDb db)
{
  public DbSet<Customer> Customers => db.Customers;
}
