using Microsoft.EntityFrameworkCore;
using SampleProgram.Entities;
using SampleProgram.Repository;

namespace SampleProgram.Domains;

public partial class StaffsDomain(PrimaryDb db)
{
  // These codes should be generated by the source generator
  public DbSet<Staff> Staffs => db.Staffs;
  public DbSet<StaffSchedule> StaffSchedules => db.StaffSchedules;
  private DbSet<StaffDetails> StaffDetails => db.StaffDetails;

  // User defined domain logic
  public IAsyncEnumerable<Staff> GetStaffsOnDateAsync(DateTime date)
  {
    var start = date.Date;
    var end = date.AddDays(1);
    return db
      .StaffSchedules
      .Where(x => start <= x.Start && x.Start < end)
      .Include(x => x.Staff.Details)
      .Select(x => x.Staff)
      .ToAsyncEnumerable();
  }
}
